# Generated by Django 4.2.1 on 2023-05-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=128)),
                ('writer', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.press')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.section')),
            ],
        ),
    ]
